/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from "react";
import { 
  CheckCircle, 
  XCircle, 
  Copy, 
  FileText, 
  Award, 
  AlertCircle, 
  Sparkles, 
  Download, 
  Printer, 
  RotateCcw,
  Check,
  TrendingUp,
  BrainCircuit,
  BookmarkCheck,
  ShieldAlert,
  ArrowRight
} from "lucide-react";
import { 
  ResponsiveContainer, 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  Tooltip, 
  Cell,
  PieChart,
  Pie
} from "recharts";
import { ResumeAnalysisResult } from "../types";
import { generateMarkdownReport, downloadMarkdownFile } from "./ReportGenerator";

interface AnalysisDashboardProps {
  result: ResumeAnalysisResult;
  roleTitle: string;
  onReset: () => void;
}

export default function AnalysisDashboard({ result, roleTitle, onReset }: AnalysisDashboardProps) {
  const [activeTab, setActiveTab] = useState<"overview" | "keywords" | "skills" | "improvements" | "tailored">("overview");
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [animatedScore, setAnimatedScore] = useState(0);
  const [keywordFilter, setKeywordFilter] = useState<"all" | "found" | "missing">("all");

  // Format fallbacks for absolute safety in case Gemini schema has minor structural slips
  const matchPercentage = result.matchPercentage ?? 0;
  const summary = result.summary ?? "Review report below for full metrics.";
  const matchedSkills = result.matchedSkills ?? [];
  const missingSkills = result.missingSkills ?? [];
  const keywordAnalysis = result.keywordAnalysis ?? [];
  const strengths = result.strengths ?? [];
  const weaknesses = result.weaknesses ?? [];
  const improvementSuggestions = result.improvementSuggestions ?? [];
  const tailoredBullets = result.tailoredBullets ?? [];

  // Animate the needle / gauge entry
  useEffect(() => {
    const duration = 1200; // ms
    const startTime = performance.now();
    
    let animationFrameId: number;
    
    const updateScore = (now: number) => {
      const elapsed = now - startTime;
      const progress = Math.min(elapsed / duration, 1);
      // Ease out cubic
      const easedProgress = 1 - Math.pow(1 - progress, 3);
      setAnimatedScore(Math.round(easedProgress * matchPercentage));
      
      if (progress < 1) {
        animationFrameId = requestAnimationFrame(updateScore);
      }
    };
    
    animationFrameId = requestAnimationFrame(updateScore);
    return () => cancelAnimationFrame(animationFrameId);
  }, [matchPercentage]);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleDownloadMarkdown = () => {
    const content = generateMarkdownReport(result, roleTitle);
    const sanitizedTitle = roleTitle.trim().replace(/[^a-zA-Z0-9]/g, "_") || "Match";
    downloadMarkdownFile(content, `AI_Resume_Feedback_${sanitizedTitle}.md`);
  };

  const handlePrint = () => {
    window.print();
  };

  // Recharts Keyword Found vs Missing ratio
  const foundKeywordsCount = keywordAnalysis.filter(k => k.foundInResume).length;
  const missingKeywordsCount = keywordAnalysis.filter(k => !k.foundInResume).length;

  const keywordChartData = [
    { name: "Found Keywords", value: foundKeywordsCount, color: "#10b981" },
    { name: "Missing Keywords", value: missingKeywordsCount, color: "#ef4444" }
  ];

  const skillChartData = [
    { name: "Skills Matched", count: matchedSkills.length, fill: "#6366f1" },
    { name: "Critical Gaps", count: missingSkills.length, fill: "#f59e0b" }
  ];

  const filteredKeywords = keywordAnalysis.filter(item => {
    if (keywordFilter === "all") return true;
    if (keywordFilter === "found") return item.foundInResume;
    return !item.foundInResume;
  });

  // Calculate score category color mapping
  const getScoreColorClass = (score: number) => {
    if (score >= 80) return "text-emerald-600 bg-emerald-50 border-emerald-100";
    if (score >= 50) return "text-amber-600 bg-amber-50 border-amber-100";
    return "text-rose-600 bg-rose-50 border-rose-100";
  };

  const getScoreStroke = (score: number) => {
    if (score >= 80) return "#10b981"; // Emerald
    if (score >= 50) return "#f59e0b"; // Amber
    return "#ef4444"; // Rose
  };

  return (
    <div className="space-y-6">
      {/* Print-Only Header */}
      <div className="hidden print:block mb-8 border-b border-slate-200 pb-4">
        <h1 className="text-3xl font-bold font-sans text-slate-900">AI Resume Audit Report</h1>
        <p className="text-sm text-slate-500 mt-1">Generated by Google AI Studio Gemini API</p>
        <div className="mt-4 grid grid-cols-2 gap-4 text-xs font-mono">
          <div><strong>Position:</strong> {roleTitle || "Target Job Description"}</div>
          <div><strong>ATS Compatibility Score:</strong> {matchPercentage}%</div>
        </div>
      </div>

      {/* Dashboard Top Card (Action Control Panel) */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-xs p-6 print:hidden">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <span className="text-xs font-semibold text-indigo-600 uppercase tracking-wider">Analysis complete</span>
            <h2 className="text-2xl font-bold text-slate-905 font-sans mt-0.5">Resume Dashboard</h2>
            <div className="flex items-center gap-2 mt-1 sm:mt-0">
              <span className="text-xs text-slate-510">Optimizing for:</span>
              <span className="text-xs font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded-md truncate max-w-xs">{roleTitle || "Target Role"}</span>
            </div>
          </div>
          
          <div className="flex flex-wrap items-center gap-2.5 w-full sm:w-auto">
            <button
              onClick={handleDownloadMarkdown}
              className="flex-1 sm:flex-initial flex items-center justify-center gap-1.5 px-3 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-200 rounded-xl hover:bg-slate-50 active:scale-98 transition-all duration-150"
            >
              <Download className="w-4 h-4" />
              Download report
            </button>
            <button
              onClick={handlePrint}
              className="flex-1 sm:flex-initial flex items-center justify-center gap-1.5 px-3 py-2 text-sm font-medium text-slate-755 bg-white border border-slate-200 rounded-xl hover:bg-slate-50 active:scale-98 transition-all duration-150"
            >
              <Printer className="w-4 h-4" />
              Print / Save PDF
            </button>
            <button
              onClick={onReset}
              className="w-full sm:w-auto flex items-center justify-center gap-1.5 px-3.5 py-2 text-sm font-medium text-white bg-indigo-650 rounded-xl hover:bg-indigo-700 active:scale-98 shadow-sm shadow-indigo-100 transition-all duration-150"
            >
              <RotateCcw className="w-4 h-4" />
              Analyze another
            </button>
          </div>
        </div>
      </div>

      {/* Grid Layout: Main Score Gauge & Chart Overview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
        {/* Match Percentage Display Card (5 columns) */}
        <div className="bg-white rounded-2xl border border-slate-100 shadow-xs p-6 lg:col-span-5 flex flex-col justify-between">
          <div className="text-center sm:text-left">
            <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">ATS Score Alignment</h3>
            <p className="text-xs text-slate-400 mt-0.5">Calculated based on skills, weights, content depth</p>
          </div>

          <div className="flex flex-col items-center justify-center my-6 relative">
            {/* SVG Arc Gauge */}
            <svg className="w-48 h-48 transform -rotate-90">
              {/* Target static arc */}
              <circle
                cx="96"
                cy="96"
                r="78"
                stroke="#f1f5f9"
                strokeWidth="11"
                fill="transparent"
              />
              {/* Dynamic filled arc */}
              <circle
                cx="96"
                cy="96"
                r="78"
                stroke={getScoreStroke(matchPercentage)}
                strokeWidth="12"
                fill="transparent"
                strokeDasharray={490}
                strokeDashoffset={490 - (490 * animatedScore) / 100}
                strokeLinecap="round"
                className="transition-all duration-100 ease-out"
              />
            </svg>
            <div className="absolute flex flex-col items-center justify-center">
              <span className="text-4xl sm:text-5xl font-black font-sans tracking-tight text-slate-900">{animatedScore}%</span>
              <span className={`text-[11px] font-semibold tracking-wide uppercase px-2.5 py-0.5 rounded-full mt-2 border ${getScoreColorClass(matchPercentage)}`}>
                {matchPercentage >= 80 ? "High Match" : matchPercentage >= 50 ? "Moderate fit" : "Requires revision"}
              </span>
            </div>
          </div>

          <div className="bg-slate-50 rounded-xl p-3 text-center text-xs font-mono text-slate-510 border border-slate-100">
            {matchPercentage >= 80 
              ? "✨ Great alignment! Your keywords are optimized for recruiters."
              : matchPercentage >= 50 
              ? "⚡ Good base. Focus on addressing the missing skills listed below."
              : "⚠️ Low index. Add direct phrasing amendments to pass ATS screening."
            }
          </div>
        </div>

        {/* Executive summary & stats comparison (7 columns) */}
        <div className="bg-white rounded-2xl border border-slate-100 shadow-xs p-6 lg:col-span-7 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-1.5 text-indigo-650 mb-1">
              <BrainCircuit className="w-5 h-5 shrink-0" />
              <h3 className="text-sm font-semibold uppercase tracking-wider">Executive Overview</h3>
            </div>
            <div className="prose prose-slate max-w-none">
              <p className="text-sm text-slate-600 leading-relaxed font-sans">{summary}</p>
            </div>
          </div>

          <div className="border-t border-slate-100 pt-5 mt-5">
            <h4 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Core Match Metrics Comparison</h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Recharts Skill distribution counts */}
              <div className="h-28">
                <ResponsiveContainer width="99%" height="100%">
                  <BarChart data={skillChartData} margin={{ top: 5, right: 5, left: -25, bottom: 5 }} layout="vertical">
                    <XAxis type="number" hide />
                    <YAxis dataKey="name" type="category" style={{ fontSize: "10px", fontWeight: "600", fill: "#475569" }} width={80} />
                    <Tooltip cursor={{ fill: "transparent" }} contentStyle={{ fontSize: "11px", borderRadius: "8px" }} />
                    <Bar dataKey="count" radius={[0, 4, 4, 0]} barSize={12}>
                      {skillChartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fill} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Keyword distribution pie ratio */}
              <div className="flex items-center justify-between border-l border-slate-100 pl-4">
                <div className="space-y-1.5">
                  <div className="flex items-center gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-emerald-500"></div>
                    <span className="text-[11px] font-medium text-slate-600">Found: {foundKeywordsCount}</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-rose-500"></div>
                    <span className="text-[11px] font-medium text-slate-600">Missing: {missingKeywordsCount}</span>
                  </div>
                  <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider border-t border-slate-100 pt-1">Keyword compliance</p>
                </div>

                <div className="w-24 h-24 shrink-0">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Tooltip contentStyle={{ fontSize: "10px", borderRadius: "6px" }} />
                      <Pie
                        data={keywordChartData}
                        cx="50%"
                        cy="50%"
                        innerRadius={18}
                        outerRadius={36}
                        paddingAngle={3}
                        dataKey="value"
                      >
                        {keywordChartData.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.color} />
                        ))}
                      </Pie>
                    </PieChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Grid Layout: Strengths vs Weaknesses (Split columns) */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths card (Green themes) */}
        <div className="bg-emerald-50/20 rounded-2xl border border-emerald-100/50 p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4 text-emerald-800">
              <BookmarkCheck className="w-5 h-5 shrink-0" />
              <h3 className="text-base font-semibold font-sans">Core ATS Alignment Strengths</h3>
            </div>
            
            {strengths.length > 0 ? (
              <ul className="space-y-4">
                {strengths.map((item, idx) => (
                  <li key={idx} className="flex gap-2.5 items-start">
                    <CheckCircle className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                    <div>
                      <h4 className="text-xs font-semibold text-emerald-950 font-sans">{item.title}</h4>
                      <p className="text-xs text-emerald-800/80 leading-relaxed mt-0.5">{item.description}</p>
                    </div>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-slate-500 italic">No standout matching strengths found. Review skill listings and incorporate recommended experiences.</p>
            )}
          </div>
        </div>

        {/* Gaps/Weaknesses card (Amber themes) */}
        <div className="bg-amber-50/20 rounded-2xl border border-amber-100/50 p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4 text-amber-805">
              <ShieldAlert className="w-5 h-5 shrink-0" />
              <h3 className="text-base font-semibold font-sans">Gaps & Targeted Risk Vectors</h3>
            </div>

            {weaknesses.length > 0 ? (
              <ul className="space-y-4">
                {weaknesses.map((item, idx) => (
                  <li key={idx} className="flex gap-2.5 items-start">
                    <AlertCircle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                    <div>
                      <h4 className="text-xs font-semibold text-amber-955 font-sans">{item.title}</h4>
                      <p className="text-xs text-amber-800/80 leading-relaxed mt-0.5">{item.description}</p>
                    </div>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-xs text-slate-500 italic">Excellent! No severe discrepancies or structural blocks detected in this review cycle.</p>
            )}
          </div>
        </div>
      </div>

      {/* Dynamic Tab Panel Container (Primary detailed audits) */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-xs overflow-hidden">
        {/* Tab switcher headers */}
        <div className="border-b border-slate-100 bg-slate-50/50 p-2 text-xs flex flex-wrap gap-1 print:hidden">
          <button
            onClick={() => setActiveTab("overview")}
            className={`px-4 py-2 rounded-xl font-medium cursor-pointer transition-all duration-150 ${activeTab === "overview" ? "bg-white text-indigo-600 shadow-xs border border-indigo-50" : "text-slate-600 hover:bg-slate-100"}`}
          >
            Dashboard Summary
          </button>
          <button
            onClick={() => setActiveTab("keywords")}
            className={`px-4 py-2 rounded-xl font-medium cursor-pointer transition-all duration-150 ${activeTab === "keywords" ? "bg-white text-indigo-600 shadow-xs border border-indigo-50" : "text-slate-600 hover:bg-slate-100"}`}
          >
            Keywords ({keywordAnalysis.length})
          </button>
          <button
            onClick={() => setActiveTab("skills")}
            className={`px-4 py-2 rounded-xl font-medium cursor-pointer transition-all duration-150 ${activeTab === "skills" ? "bg-white text-indigo-600 shadow-xs border border-indigo-50" : "text-slate-600 hover:bg-slate-100"}`}
          >
            Skills Comparison
          </button>
          <button
            onClick={() => setActiveTab("improvements")}
            className={`px-4 py-2 rounded-xl font-medium cursor-pointer transition-all duration-150 ${activeTab === "improvements" ? "bg-white text-indigo-600 shadow-xs border border-indigo-50" : "text-slate-600 hover:bg-slate-100"}`}
          >
            Phrasing Revisions
          </button>
          <button
            onClick={() => setActiveTab("tailored")}
            className={`px-4 py-2 rounded-xl font-medium cursor-pointer transition-all duration-150 ${activeTab === "tailored" ? "bg-white text-indigo-600 shadow-xs border border-indigo-50" : "text-[12px] text-slate-600 hover:bg-slate-100"}`}
          >
            <span className="flex items-center gap-1">
              <Sparkles className="w-3 h-3 text-amber-500 fill-amber-500 shrink-0" />
              Tailored Bullets
            </span>
          </button>
        </div>

        {/* Tab content bodies */}
        <div className="p-6">
          {/* TAB 1: DASHBOARD SUMMARY (Overview List) */}
          <div className={activeTab === "overview" ? "block space-y-6" : "hidden print:block print:space-y-6"}>
            <div className="space-y-6">
              <div>
                <h3 className="text-base font-bold text-slate-900 font-sans">Resume Match Key Metrics</h3>
                <p className="text-xs text-slate-400 mt-0.5">Summary of major points identified across individual review panels.</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="border border-slate-100 rounded-xl p-4 bg-slate-50/20">
                  <div className="text-[11px] font-semibold text-indigo-600 uppercase tracking-widest mb-1">Keywords Identified</div>
                  <div className="flex items-baseline gap-1">
                    <span className="text-2xl font-bold text-slate-800">{foundKeywordsCount}</span>
                    <span className="text-slate-400 text-xs">/ {keywordAnalysis.length} total</span>
                  </div>
                  <p className="text-xs text-slate-500 leading-normal mt-1 flex items-center gap-1.5">
                    <ArrowRight className="w-3 h-3 text-slate-400 shrink-0" />
                    {missingKeywordsCount} critical keywords missing in comparison.
                  </p>
                </div>

                <div className="border border-slate-100 rounded-xl p-4 bg-slate-50/20">
                  <div className="text-[11px] font-semibold text-emerald-600 uppercase tracking-widest mb-1">Matched Capabilities</div>
                  <div className="flex items-baseline gap-1">
                    <span className="text-2xl font-bold text-slate-800">{matchedSkills.length}</span>
                    <span className="text-slate-400 text-xs">skills overlapped</span>
                  </div>
                  <p className="text-xs text-slate-500 leading-normal mt-1 flex items-center gap-1.5">
                    <ArrowRight className="w-3 h-3 text-slate-400 shrink-0" />
                    Qualified technical and soft skill vectors checked.
                  </p>
                </div>

                <div className="border border-slate-100 rounded-xl p-4 bg-slate-50/20">
                  <div className="text-[11px] font-semibold text-amber-600 uppercase tracking-widest mb-1">Optimizations Ready</div>
                  <div className="flex items-baseline gap-1">
                    <span className="text-2xl font-bold text-slate-800">{improvementSuggestions.length}</span>
                    <span className="text-slate-400 text-xs">phrasing recommendations</span>
                  </div>
                  <p className="text-xs text-slate-500 leading-normal mt-1 flex items-center gap-1.5">
                    <ArrowRight className="w-3 h-3 text-slate-400 shrink-0" />
                    Rewrite suggestions with recruiter metrics.
                  </p>
                </div>
              </div>

              <div className="bg-indigo-50/20 border border-indigo-100/30 rounded-xl p-4 mt-2 flex items-start gap-4">
                <div className="p-2 bg-indigo-50 rounded-lg text-indigo-650 shrink-0">
                  <Sparkles className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="text-sm font-semibold text-indigo-950 font-sans">Try out Tailored Resume Bullets!</h4>
                  <p className="text-xs text-indigo-800 leading-relaxed mt-1">
                    Our AI has restructured specific bullets in your work history to incorporate metrics and top keywords naturally. Check out the <span onClick={() => setActiveTab("tailored")} className="underline font-semibold cursor-pointer">Tailored Bullets</span> tab to see them!
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* TAB 2: KEYWORDS */}
          <div className={activeTab === "keywords" ? "block space-y-6" : "hidden print:block print:break-before-page"}>
            <div className="space-y-6">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                <div>
                  <h3 className="text-base font-bold text-slate-900 font-sans">Keyword Audit & Compliance</h3>
                  <p className="text-xs text-slate-400">Target phrases and technology buzzwords analyzed directly from the job description.</p>
                </div>
                {/* Filter selector layout */}
                <div className="bg-slate-100 p-1 rounded-lg text-xs flex gap-1 print:hidden">
                  <button
                    onClick={() => setKeywordFilter("all")}
                    className={`px-3 py-1.5 rounded-md cursor-pointer transition-colors ${keywordFilter === "all" ? "bg-white font-semibold text-slate-800 shadow-xs" : "text-slate-500 hover:text-slate-855"}`}
                  >
                    All ({keywordAnalysis.length})
                  </button>
                  <button
                    onClick={() => setKeywordFilter("found")}
                    className={`px-3 py-1.5 rounded-md cursor-pointer transition-colors ${keywordFilter === "found" ? "bg-white font-semibold text-slate-800 shadow-xs" : "text-slate-500 hover:text-slate-855"}`}
                  >
                    Found ({foundKeywordsCount})
                  </button>
                  <button
                    onClick={() => setKeywordFilter("missing")}
                    className={`px-3 py-1.5 rounded-md cursor-pointer transition-colors ${keywordFilter === "missing" ? "bg-white font-semibold text-slate-800 shadow-xs" : "text-slate-500 hover:text-slate-855"}`}
                  >
                    Missing ({missingKeywordsCount})
                  </button>
                </div>
              </div>

              {filteredKeywords.length > 0 ? (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {filteredKeywords.map((item, idx) => (
                    <div 
                      key={idx} 
                      className={`border p-4 rounded-xl flex items-start gap-3.5 transition-all duration-150 ${
                        item.foundInResume 
                          ? "bg-slate-50/50 border-slate-150 hover:border-slate-300" 
                          : "bg-red-50/10 border-rose-100/50 hover:bg-rose-50/10"
                      }`}
                    >
                      {item.foundInResume ? (
                        <CheckCircle className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
                      ) : (
                        <XCircle className="w-5 h-5 text-rose-500 shrink-0 mt-0.5" />
                      )}
                      <div className="space-y-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="text-sm font-bold text-slate-800 leading-tight">{item.keyword}</span>
                          <span className={`text-[10px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded ${
                            item.foundInResume 
                              ? "bg-emerald-50 text-emerald-700 border border-emerald-100" 
                              : "bg-rose-50 text-rose-700 border border-rose-100"
                          }`}>
                            {item.foundInResume ? "Found in resume" : "Missing keyword"}
                          </span>
                        </div>
                        <p className="text-xs text-slate-500 leading-relaxed font-sans">{item.recommendation}</p>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 border border-dashed border-slate-200 rounded-xl">
                  <p className="text-sm text-slate-500 italic">No keywords match this filter category.</p>
                </div>
              )}
            </div>
          </div>

          {/* TAB 3: SKILLS COMPARISON */}
          <div className={activeTab === "skills" ? "block space-y-6" : "hidden print:block print:break-before-page"}>
            <div className="space-y-6">
              <div>
                <h3 className="text-base font-bold text-slate-900 font-sans">Skills Alignment Review</h3>
                <p className="text-xs text-slate-400 mt-0.5">Overlaps and omissions of required hard and soft core credentials.</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-stretch">
                {/* Overlapped skills list */}
                <div className="border border-slate-150 rounded-xl p-5 bg-slate-50/20">
                  <h4 className="text-sm font-bold text-emerald-950 flex items-center gap-1.5 mb-4 border-b border-emerald-100/50 pb-2">
                    <CheckCircle className="w-4.5 h-4.5 text-emerald-600" />
                    Matched Capabilities ({matchedSkills.length})
                  </h4>

                  {matchedSkills.length > 0 ? (
                    <div className="flex flex-wrap gap-2">
                      {matchedSkills.map((item, idx) => (
                        <div key={idx} className="flex flex-col bg-white border border-slate-200 shadow-xs px-3 py-1.5 rounded-lg text-xs">
                          <span className="font-bold text-slate-800">{item.skill}</span>
                          <span className="text-[9px] uppercase tracking-wider text-slate-400 mt-0.5 font-semibold">{item.category}</span>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-xs text-slate-500 italic py-4 text-center">No explicit matching skills found. Expand technical sections.</p>
                  )}
                </div>

                {/* Missing required skills with severity */}
                <div className="border border-amber-150 rounded-xl p-5 bg-slate-50/20">
                  <h4 className="text-sm font-bold text-amber-955 flex items-center gap-1.5 mb-4 border-b border-amber-100/50 pb-2">
                    <AlertCircle className="w-4.5 h-4.5 text-amber-600" />
                    Missing Required Skills ({missingSkills.length})
                  </h4>

                  {missingSkills.length > 0 ? (
                    <div className="space-y-3">
                      {missingSkills.map((item, idx) => (
                        <div key={idx} className="border border-amber-100 bg-amber-50/10 p-3 rounded-lg flex gap-2.5 items-start">
                          <span className={`text-[9px] font-black uppercase px-2 py-0.5 rounded shrink-0 border ${
                            item.importance === "High" 
                              ? "bg-rose-55 text-rose-700 border-rose-100" 
                              : item.importance === "Medium"
                              ? "bg-amber-100 text-amber-700 border-amber-200"
                              : "bg-slate-100 text-slate-700 border-slate-200"
                          }`}>
                            {item.importance} Importance
                          </span>
                          <div className="space-y-0.5 min-w-0">
                            <h5 className="text-xs font-bold text-slate-850 truncate">{item.skill}</h5>
                            <p className="text-xs text-slate-500 leading-relaxed font-sans mt-0.5">{item.reason}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-xs text-slate-500 italic py-4 text-center">Incredible! All critical JD tools are mapped onto the resume.</p>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* TAB 4: PHRASING IMPROVEMENTS */}
          <div className={activeTab === "improvements" ? "block space-y-6" : "hidden print:block print:break-before-page"}>
            <div className="space-y-6">
              <div>
                <h3 className="text-base font-bold text-slate-900 font-sans">Specific Section Phrasing Recommendations</h3>
                <p className="text-xs text-slate-400 mt-0.5">Before and after edits generated using action-verbs and metric models.</p>
              </div>

              {improvementSuggestions.length > 0 ? (
                <div className="space-y-5">
                  {improvementSuggestions.map((sug, idx) => (
                    <div key={idx} className="border border-slate-150 rounded-xl overflow-hidden hover:border-slate-350 transition-colors duration-150">
                      {/* Section tag header */}
                      <div className="bg-slate-55 border-b border-slate-150 px-4 py-2.5 flex items-center justify-between text-xs">
                        <span className="font-bold text-slate-800 uppercase tracking-wider">
                          Section Location: <span className="text-indigo-650">{sug.section}</span>
                        </span>
                        <span className="text-slate-405">Actionable Suggestion #{idx + 1}</span>
                      </div>

                      <div className="p-4 space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          {sug.currentText ? (
                            <div className="space-y-1">
                              <div className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest">Your Current Wording:</div>
                              <p className="text-xs font-mono p-3 bg-red-50/10 border border-slate-100 text-slate-600 rounded-lg whitespace-pre-wrap leading-relaxed italic">
                                "{sug.currentText}"
                              </p>
                            </div>
                          ) : null}

                          <div className={`space-y-1 ${sug.currentText ? "" : "col-span-2"}`}>
                            <div className="flex items-center justify-between">
                              <div className="text-[10px] font-bold text-indigo-600 uppercase tracking-widest flex items-center gap-1.5">
                                <Sparkles className="w-3.5 h-3.5 fill-indigo-100" />
                                Recommended Optimized Wording:
                              </div>
                              <button
                                onClick={() => copyToClipboard(sug.suggestedText, `sug-${idx}`)}
                                className="flex items-center gap-1.5 px-2 py-0.5 text-[11px] font-semibold text-indigo-700 bg-indigo-50 border border-indigo-100 rounded-md hover:bg-indigo-100/80 transition-colors cursor-pointer print:hidden"
                              >
                                {copiedId === `sug-${idx}` ? (
                                  <>
                                    <Check className="w-3 h-3" />
                                    Copied!
                                  </>
                                ) : (
                                  <>
                                    <Copy className="w-3 h-3" />
                                    Copy wording
                                  </>
                                )}
                              </button>
                            </div>
                            <p className="text-xs font-mono p-3 bg-indigo-50/10 border border-indigo-100/50 text-indigo-950 rounded-lg whitespace-pre-wrap leading-relaxed font-semibold">
                              {sug.suggestedText}
                            </p>
                          </div>
                        </div>

                        {/* ATC reasoning column */}
                        <div className="bg-slate-50 rounded-lg p-3 text-xs leading-relaxed text-slate-600 border border-slate-100 flex items-start gap-2">
                          <CheckCircle className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                          <div>
                            <strong className="text-slate-800">Recruiter Rationale:</strong> {sug.explanation}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 border border-dashed border-slate-200 rounded-xl">
                  <p className="text-sm text-slate-500 italic">No specific structural text modifications required.</p>
                </div>
              )}
            </div>
          </div>

          {/* TAB 5: TAILORED SHOWN BULLETS */}
          <div className={activeTab === "tailored" ? "block space-y-6" : "hidden print:block print:break-before-page"}>
            <div className="space-y-6">
              <div>
                <div className="flex items-center gap-1.5 text-indigo-650">
                  <Sparkles className="w-5 h-5" />
                  <h3 className="text-base font-bold text-slate-900 font-sans">Core Resume Bullets Restructuring</h3>
                </div>
                <p className="text-xs text-slate-400 mt-0.5">Pre-tailored impact statements custom built for instant inclusion into your target document.</p>
              </div>

              {tailoredBullets.length > 0 ? (
                <div className="space-y-5">
                  {tailoredBullets.map((bullet, idx) => (
                    <div key={idx} className="border border-indigo-100 rounded-2xl overflow-hidden hover:border-indigo-200 transition-all duration-150 shadow-xs">
                      {/* Sub-header */}
                      <div className="bg-gradient-to-r from-indigo-50/50 to-white border-b border-indigo-55 px-4 py-3 flex items-center justify-between text-xs">
                        <span className="font-bold text-indigo-900 flex items-center gap-1.5">
                          <TrendingUp className="w-4 h-4 text-indigo-600" />
                          Restructured Performance Statement #{idx + 1}
                        </span>
                        <button
                          onClick={() => copyToClipboard(bullet.tailoredBullet, `tailored-${idx}`)}
                          className="flex items-center gap-1 px-2.5 py-1 text-[11px] font-bold text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 active:scale-95 transition-all duration-150 shadow-sm cursor-pointer print:hidden"
                        >
                          {copiedId === `tailored-${idx}` ? (
                            <>
                              <Check className="w-3.5 h-3.5" />
                              Copied!
                            </>
                          ) : (
                            <>
                              <Copy className="w-3.5 h-3.5" />
                              Copy statement
                            </>
                          )}
                        </button>
                      </div>

                      {/* Phrasing body comparisons */}
                      <div className="p-4 space-y-3.5">
                        <div className="space-y-1">
                          <span className="text-[10px] font-bold text-indigo-600 uppercase tracking-widest block">Optimized Wording:</span>
                          <span className="text-[13px] font-semibold text-slate-800 leading-relaxed font-sans">{bullet.tailoredBullet}</span>
                        </div>

                        {bullet.originalBullet && (
                          <div className="border-t border-slate-100 pt-3 space-y-1">
                            <span className="text-[10px] font-medium text-slate-400 uppercase tracking-widest block">Original Reference Bullet:</span>
                            <span className="text-xs text-slate-500 leading-normal block italic">"{bullet.originalBullet}"</span>
                          </div>
                        )}

                        <div className="bg-slate-50/80 rounded-xl p-3 text-xs text-slate-600 border border-slate-100 font-sans leading-relaxed flex gap-2">
                          <CheckCircle className="w-4.5 h-4.5 text-emerald-600 shrink-0 mt-0.5" />
                          <div>
                            <strong className="text-slate-800">Recruiter Feasibility Justification:</strong> {bullet.explanation}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 border border-dashed border-slate-200 rounded-xl">
                  <p className="text-sm text-slate-500 italic">No custom tailored bullets created for this role type.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
